import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Check } from "lucide-react";
import { BrandSymbol, SiteShell } from "@/components/site-shell";
import { Button } from "@/components/ui/button";
import heroImage from "@/assets/loma-hero-premium.jpg";
import padsImage from "@/assets/loma-product-pads.jpg";

export const Route = createFileRoute("/about")({ head: () => ({ meta: [{ title: "عن لوما | عناية هادئة وواضحة" }, { name: "description", content: "اكتشفي فلسفة لوما في تنظيف البشرة بلطف وفعالية، دون تعقيد أو قسوة." }, { property: "og:title", content: "عن لوما" }, { property: "og:description", content: "عناية هادئة تبدأ من تنظيف بسيط وفعّال." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: AboutPage });

function AboutPage() { return <SiteShell><section className="grid min-h-[72svh] md:grid-cols-2"><div className="flex items-center px-6 py-16 md:px-14 lg:px-24"><div className="max-w-xl"><p className="mb-4 text-xs font-semibold text-gold">عن لوما</p><h1 className="text-5xl font-semibold leading-tight md:text-7xl">عناية واضحة.<br />وهدوء تشعرين به.</h1><p className="mt-7 text-base leading-8 text-muted-foreground">بدأت لوما من فكرة بسيطة: أن تنظيف البشرة لا يجب أن يكون خطوة قاسية. نصمم أساسيات يومية تجمع بين الفعالية واللطف، لتبدأ العناية بإحساس نظيف ومطمئن.</p></div></div><div className="min-h-[55svh]"><img src={heroImage} alt="منتجات لوما للعناية بالبشرة" className="size-full object-cover" /></div></section><section className="bg-card px-5 py-20 md:px-10 md:py-28"><div className="mx-auto grid max-w-[1200px] gap-12 md:grid-cols-[0.8fr_1.2fr] md:gap-20"><div><BrandSymbol className="mb-6 size-12" /><h2 className="text-3xl font-semibold leading-tight md:text-5xl">النقاء ليس مبالغة.<br />إنه توازن.</h2></div><div className="space-y-7 text-base leading-9 text-muted-foreground"><p>نؤمن أن المنتجات التي تستخدمينها كل يوم يجب أن تكون مفهومة ومريحة. لذلك تركز لوما على تجربة تنظيف مباشرة: تزيل المكياج، تحترم منطقة العينين، ولا تترك إحساسًا دهنيًا.</p><p>من العبوة الهادئة إلى الوسادة الناعمة، صُمم كل تفصيل ليجعل الروتين أقرب إلى لحظة عناية، لا مهمة إضافية.</p></div></div></section><section className="grid bg-secondary md:grid-cols-2"><div className="min-h-[520px]"><img src={padsImage} alt="وسادات لوما القطنية" className="size-full object-cover" /></div><div className="flex items-center px-6 py-16 md:px-14 lg:px-24"><div className="w-full"><p className="mb-4 text-xs font-semibold text-gold">وعد لوما</p><h2 className="text-4xl font-semibold leading-tight md:text-5xl">فعّالة في التنظيف.<br />هادئة على البشرة.</h2><div className="mt-10 divide-y divide-border border-y border-border">{["تركيبات بلا عطر", "لطافة حول منطقة العين", "إزالة فعّالة للمكياج", "ملمس نظيف وغير دهني"].map((item) => <div key={item} className="flex items-center gap-4 py-5"><Check className="size-5 shrink-0 text-gold" /><span>{item}</span></div>)}</div><Button asChild variant="luxury" size="luxury" className="mt-9 rounded-none"><Link to="/products">اكتشفي المجموعة <ArrowLeft /></Link></Button></div></div></section></SiteShell>; }